language: ruby
rvm:
 - 2.6.3
script:
 - chmod +x ./build.sh
 - ./build.sh

#install:
#  - bundle install
#  - gem install jekyll
#  - gem install jekyll-paginate
#  - gem install jekyll-sitemap


branches:
  only:
  - master
env:
  global:
#  - JEKYLL_ENV=production
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
addons:
  apt:
    packages:
    - libcurl4-openssl-dev
#    - ncftp
os: linux
cache: bundler
notifications:
  email: false
before_install:
- openssl aes-256-cbc -K $encrypted_70235cfcdc01_key -iv $encrypted_70235cfcdc01_iv
  -in travis_ssh_key.enc -out travis_ssh_key -d

after_success:
# - ssh -i ~/.ssh/deploy_ecdsa -p 2202 root@47.74.135.220 "mkdir /home/jekyll/_content/"
# - scp -i ~/.ssh/deploy_ecdsa -r -P 2202 _site/* root@47.74.135.220:/home/jekyll/_content/
 - rsync -rv -delete -e 'ssh -o stricthostkeychecking=no -i ~/.ssh/deploy_ecdsa -p 2202' $TRAVIS_BUILD_DIR/_site blog@47.74.135.220:/var/www/html/blog/_site
